# Generated by Django 3.2.23 on 2024-03-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('heading', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('btn_card', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Card',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='carousel_videos/')),
                ('carousel_number', models.IntegerField(default='0')),
                ('image_class', models.TextField(default='If carousel number = 1 then image class = image_first and css_class = first', max_length=180)),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('extra_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('btn_main_first', models.TextField(blank=True, default='Important : use this button for 1st carousel image only', max_length=200, null=True)),
                ('btn_sub_first', models.TextField(blank=True, default='Important : use this button for 1st carousel image only', max_length=200, null=True)),
                ('btn_main_second', models.TextField(blank=True, default='Important : use this button for 2nd carousel image only', max_length=200, null=True)),
                ('btn_sub_second', models.TextField(blank=True, default='Important : use this button for 2nd carousel image only', max_length=200, null=True)),
                ('btn_main_third', models.TextField(blank=True, default='Important : use this button for 3th carousel image only', max_length=200, null=True)),
                ('btn_sub_third', models.TextField(blank=True, default='Important : use this button for 3th carousel image only', max_length=200, null=True)),
                ('css_class', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['carousel_number'],
            },
        ),
        migrations.CreateModel(
            name='OfferText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title1', models.TextField(blank=True, max_length=200, null=True)),
                ('offer_title2', models.TextField(blank=True, max_length=200, null=True)),
                ('offer_title3', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Offer Text',
            },
        ),
        migrations.CreateModel(
            name='TextOnHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('heading', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('btn_text', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Text below Carousel',
            },
        ),
    ]
